#!/bin/sh
# Regenerate merlin16_shortfin_ucode.h from the vendor U-Boot header.
#
# Source (GPL, shipped by Cudy/Broadcom for this board):
#   .../u-boot-2019.07/drivers/net/bcmbca/phy/Serdes146Class/merlin16_shortfin_ucode_image.h
# (byte-identical to .../phy/merlin_shortfin/merlin16_shortfin_ucode_image.h)
#
# The header is a C array literal; we re-emit it verbatim as a static const u8[]
# so nothing is hand-typed.  SIZE/CRC/VERSION are taken from the same header.
set -e
GPL=${GPL:-/home/n8n/cudy_be3600/gpl/openwrt/21.02/package/extra/bcm/src}
SRC=$GPL/bcm-bootloader/bootloaders/u-boot-2019.07/drivers/net/bcmbca/phy/Serdes146Class/merlin16_shortfin_ucode_image.h
OUT=$(dirname "$0")/merlin16_shortfin_ucode.h

VER=$(sed -n 's/.*UCODE_IMAGE_VERSION *"\([^"]*\)".*/\1/p' "$SRC")
SIZE=$(sed -n 's/.*UCODE_IMAGE_SIZE *\([0-9]*\).*/\1/p' "$SRC")
CRC=$(sed -n 's/.*UCODE_IMAGE_CRC *\(0x[0-9a-fA-F]*\).*/\1/p' "$SRC")
MD5=$(md5sum "$SRC" | cut -d' ' -f1)

{
  echo "/* SPDX-License-Identifier: GPL-2.0 */"
  echo "/*"
  echo " * Merlin16-shortfin PMD microcode image."
  echo " * GENERATED by gen_ucode.sh from the vendor U-Boot GPL header:"
  echo " *   drivers/net/bcmbca/phy/Serdes146Class/merlin16_shortfin_ucode_image.h"
  echo " *   md5 $MD5"
  echo " * DO NOT EDIT BY HAND -- re-run gen_ucode.sh instead."
  echo " */"
  echo "#ifndef _MERLIN16_SHORTFIN_UCODE_H_"
  echo "#define _MERLIN16_SHORTFIN_UCODE_H_"
  echo
  echo "#define MERLIN16_UCODE_VERSION \"$VER\""
  echo "#define MERLIN16_UCODE_SIZE    $SIZE"
  echo "#define MERLIN16_UCODE_CRC     $CRC"
  echo
  echo "static const u8 merlin16_shortfin_ucode[MERLIN16_UCODE_SIZE] = {"
  # everything between the opening '{' of the array and the closing '};'
  sed -n '/merlin16_shortfin_ucode_image\[/,/^};/p' "$SRC" | sed '1d;$d'
  echo "};"
  echo
  echo "#endif /* _MERLIN16_SHORTFIN_UCODE_H_ */"
} > "$OUT"

echo "wrote $OUT  (version $VER, $SIZE bytes, crc $CRC)"
