/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated by triaging/shim/wiphy-h14/probe.py from configured headers. */
/* Pair tables old->native. Shared bits are numerically identical (by */
/* construction from the same headers the shim compiles against); traps */
/* below must never be copied: old-only bits have a different native */
/* meaning, native-only bits must never be fabricated from old input. */
#ifndef BCM_SHIM_WIPHY_FLAGS_H
#define BCM_SHIM_WIPHY_FLAGS_H
#include <linux/types.h>
struct wiphy419_flag_pair { u32 old, native; };
static const struct wiphy419_flag_pair wp419_wiphy_flags[] = {
	{ 0x20, 0x20 }, /* 4ADDR_AP */
	{ 0x40, 0x40 }, /* 4ADDR_STATION */
	{ 0x80000, 0x80000 }, /* AP_PROBE_RESP_OFFLOAD */
	{ 0x4000, 0x4000 }, /* AP_UAPSD */
	{ 0x80, 0x80 }, /* CONTROL_PORT_PROTOCOL */
	{ 0x800000, 0x800000 }, /* HAS_CHANNEL_SWITCH */
	{ 0x200000, 0x200000 }, /* HAS_REMAIN_ON_CHANNEL */
	/* TRAP HAS_STATIC_WEP: old=0x1000000 absent natively, REJECT */
	{ 0x20000, 0x20000 }, /* HAVE_AP_SME */
	{ 0x100, 0x100 }, /* IBSS_RSN */
	{ 0x400, 0x400 }, /* MESH_AUTH */
	{ 0x8, 0x8 }, /* NETNS_OK */
	{ 0x100000, 0x100000 }, /* OFFCHAN_TX */
	{ 0x10, 0x10 }, /* PS_ON_BY_DEFAULT */
	{ 0x40000, 0x40000 }, /* REPORTS_OBSS */
	{ 0x400000, 0x400000 }, /* SUPPORTS_5_10_MHZ */
	{ 0x2000, 0x2000 }, /* SUPPORTS_FW_ROAM */
	{ 0x8000, 0x8000 }, /* SUPPORTS_TDLS */
	{ 0x10000, 0x10000 }, /* TDLS_EXTERNAL_SETUP */
};
static const struct wiphy419_flag_pair wp419_regulatory_flags[] = {
	{ 0x8, 0x8 }, /* COUNTRY_IE_FOLLOW_POWER */
	{ 0x10, 0x10 }, /* COUNTRY_IE_IGNORE */
	{ 0x1, 0x1 }, /* CUSTOM_REG */
	{ 0x4, 0x4 }, /* DISABLE_BEACON_HINTS */
	{ 0x20, 0x20 }, /* ENABLE_RELAX_NO_IR */
	/* TRAP IGNORE_STALE_KICKOFF: old=0x40, REJECT */
	{ 0x2, 0x2 }, /* STRICT_REG */
	{ 0x80, 0x80 }, /* WIPHY_SELF_MANAGED */
};
/* All 31 NL80211_FEATURE bits are numerically identical; u32 may be copied by value after rejecting unknown bits. */
#define WP419_FEATURE_KNOWN_MASK 0xffffdfffU
/* ext_features indices 0..41 are identical; copy old bytes 0..5, zero native 6..8. */
#define WP419_EXT_FEATURE_OLD_BYTES 6
#endif
