/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated by tools/wl_apreinit_trace.py; exact ARM AAPCS word arguments. */
noinline void bcm_shim_ap_reinit_383b34(u32 a0, u32 a1, u32 a2)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32, u32, u32) = (void *)(caller - 0x383b38 + 0x3d3304);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bsscfg_type_get@383b34 enter\n");
 original(a0, a1, a2);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bsscfg_type_get@383b34 exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_383b34);

noinline int bcm_shim_ap_reinit_383b58(u32 a0, u32 a1, u32 a2, u32 a3)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 int (*original)(u32, u32, u32, u32) = (void *)(caller - 0x383b5c + 0x3d2aa8);
 int result;
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bsscfg_reinit@383b58 enter\n");
 result = original(a0, a1, a2, a3);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bsscfg_reinit@383b58 exit rc=%d\n", result);
 return result;
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_383b58);

noinline void bcm_shim_ap_reinit_382d30(u32 a0, u32 a1, u32 a2)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32, u32, u32) = (void *)(caller - 0x382d34 + 0x3d3304);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bsscfg_type_get@382d30 enter\n");
 original(a0, a1, a2);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bsscfg_type_get@382d30 exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_382d30);

noinline int bcm_shim_ap_reinit_382d60(u32 a0, u32 a1, u32 a2, u32 a3)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 int (*original)(u32, u32, u32, u32) = (void *)(caller - 0x382d64 + 0x3d2aa8);
 int result;
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bsscfg_reinit@382d60 enter\n");
 result = original(a0, a1, a2, a3);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bsscfg_reinit@382d60 exit rc=%d\n", result);
 return result;
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_382d60);

noinline void bcm_shim_ap_reinit_382d98(u32 a0, u32 a1)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32, u32) = (void *)(caller - 0x382d9c + 0x31e6e4);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_ap_upd@382d98 enter\n");
 original(a0, a1);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_ap_upd@382d98 exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_382d98);

noinline void bcm_shim_ap_reinit_382dac(u32 a0)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32) = (void *)(caller - 0x382db0 + 0x31ec40);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_radio_mpc_upd@382dac enter\n");
 original(a0);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_radio_mpc_upd@382dac exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_382dac);

noinline void bcm_shim_ap_reinit_3d324c(u32 a0)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32) = (void *)(caller - 0x3d3250 + 0x31d5e8);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_hwrsscbs_free@3d324c enter\n");
 original(a0);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_hwrsscbs_free@3d324c exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d324c);

noinline void bcm_shim_ap_reinit_3d3254(u32 a0)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32) = (void *)(caller - 0x3d3258 + 0x31d6f4);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_proxdscbs_free@3d3254 enter\n");
 original(a0);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_proxdscbs_free@3d3254 exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d3254);

noinline int bcm_shim_ap_reinit_3d2b18(u32 a0, u32 a1)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 int (*original)(u32, u32) = (void *)(caller - 0x3d2b1c + 0x57a944);
 int result;
 if (ap_ioctl_trace) pr_info("H30_AP wlc_scbfree@3d2b18 enter\n");
 result = original(a0, a1);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_scbfree@3d2b18 exit rc=%d\n", result);
 return result;
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d2b18);

noinline void bcm_shim_ap_reinit_3d2bc8(u32 a0, u32 a1, u32 a2, u32 a3, u32 a4, u32 a5)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32, u32, u32, u32, u32, u32) = (void *)(caller - 0x3d2bcc + 0x40d9bc);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_cubby_deinit@3d2bc8 enter\n");
 original(a0, a1, a2, a3, a4, a5);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_cubby_deinit@3d2bc8 exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d2bc8);

noinline void bcm_shim_ap_reinit_3d2dac(u32 a0, u32 a1, u32 a2, u32 a3, u32 a4, u32 a5)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32, u32, u32, u32, u32, u32) = (void *)(caller - 0x3d2db0 + 0x40d9bc);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_cubby_deinit@3d2dac enter\n");
 original(a0, a1, a2, a3, a4, a5);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_cubby_deinit@3d2dac exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d2dac);

noinline int bcm_shim_ap_reinit_3d30a0(u32 a0, u32 a1, u32 a2, u32 a3, u32 a4, u32 a5, u32 a6)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 int (*original)(u32, u32, u32, u32, u32, u32, u32) = (void *)(caller - 0x3d30a4 + 0x40d898);
 int result;
 if (ap_ioctl_trace) pr_info("H30_AP wlc_cubby_init@3d30a0 enter\n");
 result = original(a0, a1, a2, a3, a4, a5, a6);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_cubby_init@3d30a0 exit rc=%d\n", result);
 return result;
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d30a0);

noinline int bcm_shim_ap_reinit_3d3160(u32 a0, u32 a1, u32 a2, u32 a3, u32 a4, u32 a5, u32 a6)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 int (*original)(u32, u32, u32, u32, u32, u32, u32) = (void *)(caller - 0x3d3164 + 0x40d898);
 int result;
 if (ap_ioctl_trace) pr_info("H30_AP wlc_cubby_init@3d3160 enter\n");
 result = original(a0, a1, a2, a3, a4, a5, a6);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_cubby_init@3d3160 exit rc=%d\n", result);
 return result;
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d3160);

noinline void bcm_shim_ap_reinit_3d30e0(u32 a0, u32 a1, u32 a2)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32, u32, u32) = (void *)(caller - 0x3d30e4 + 0x42c380);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_if_event@3d30e0 enter\n");
 original(a0, a1, a2);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_if_event@3d30e0 exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d30e0);

noinline void bcm_shim_ap_reinit_3d3110(u32 a0, u32 a1, u32 a2, u32 a3, u32 a4, u32 a5, u32 a6, u32 a7, u32 a8)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 void (*original)(u32, u32, u32, u32, u32, u32, u32, u32, u32) = (void *)(caller - 0x3d3114 + 0x42ca24);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bss_mac_event@3d3110 enter\n");
 original(a0, a1, a2, a3, a4, a5, a6, a7, a8);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_bss_mac_event@3d3110 exit\n");
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d3110);

noinline int bcm_shim_ap_reinit_3d32d0(u32 a0)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 int (*original)(u32) = (void *)(caller - 0x3d32d4 + 0x31d53c);
 int result;
 if (ap_ioctl_trace) pr_info("H30_AP wlc_hwrsscbs_alloc@3d32d0 enter\n");
 result = original(a0);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_hwrsscbs_alloc@3d32d0 exit rc=%d\n", result);
 return result;
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d32d0);

noinline int bcm_shim_ap_reinit_3d32e0(u32 a0)
{
 unsigned long caller = (unsigned long)__builtin_return_address(0);
 int (*original)(u32) = (void *)(caller - 0x3d32e4 + 0x31d658);
 int result;
 if (ap_ioctl_trace) pr_info("H30_AP wlc_proxdscbs_alloc@3d32e0 enter\n");
 result = original(a0);
 if (ap_ioctl_trace) pr_info("H30_AP wlc_proxdscbs_alloc@3d32e0 exit rc=%d\n", result);
 return result;
}
EXPORT_SYMBOL(bcm_shim_ap_reinit_3d32e0);
