// SPDX-License-Identifier: GPL-2.0-only
/*
 * shim_nvram.c — lane G: nvram backend for stock hnd.ko / wl.ko on 6.6.
 *
 * WHAT (FACT): hnd.ko imports exactly three wlcsm symbols —
 *   wlcsm_nvram_k_get / wlcsm_nvram_k_set / wlcsm_nvram_getall
 * (readelf UND; single call-site each, all inside hnd's own
 * nvram_get/set/getall wrappers at .text+0x26434/0x26438/0x26458).
 * wl.ko imports only nvram_get, which hnd.ko itself EXPORTS (its wrapper
 * tail-calls wlcsm_nvram_k_get). So these three symbols close the whole
 * kernel-nvram dependency chain transitively.
 *
 * WHY HERE, not stock bcm_knvram.ko (DECISION v3, 2026-09-07, lane G):
 * stock knvram DOES export all three via plain EXPORT_SYMBOL (FACT:
 * __ksymtab/strings of both in-repo copies — image/rootfs-overlay and the
 * gpl build_dir copy), yet hnd66.ko still failed with "Unknown symbol
 * wlcsm_nvram_k_*" on the 6.6 box (FACT, PORT_PLAN_66.md M2 blocker).
 * Cause at file level is NOT a missing export (see SHIM_LANE_G_REPORT.md
 * for the hypotheses lane H must check: stale patched copy / init abort /
 * load order). Independent of that, stock knvram is WRONG for 6.6:
 *  (a) it boots with an EMPTY tree — seeding is done by stock userspace
 *      (hndnvram.sh: `nvram kernelset` + `nvram kset`), which does not
 *      exist on our OpenWrt; every lookup would miss;
 *  (b) a shim copy collides with it ("exports duplicate symbol") — only
 *      ONE provider may be loaded. Recommendation to lane H: do NOT load
 *      stock bcm_knvram.ko; the shim below is the sole provider.
 *
 * SEMANTICS (GPL-faithful port of
 * bcmdrivers/opensource/char/bcm_knvram/impl1/src/wlcsm_nvram.c):
 *  - char *wlcsm_nvram_k_get(char *name): pointer to the stored value,
 *    NULL on miss. Lifetime: valid until the next k_set of the same key
 *    (same racy-but-static contract as stock: "kernel NVRAMs are static,
 *    not supposed to change at runtime" — wlcsm_nvram.c:207).
 *  - int wlcsm_nvram_k_set(char *name, char *value): 0 on success,
 *    1 (WLCSM_GEN_ERR, NOT negative — wlcsm_linux.h:157-158) on error.
 *    A NULL value is stored as "" (DEVIATION from stock, which would
 *    crash a later getall on strlen(NULL); no in-blob caller passes NULL).
 *  - int wlcsm_nvram_getall(char *buf, int count): "name=value\\0…\\0\\0"
 *    (double-NUL terminated, wlcsm_double_null_terminate semantics);
 *    returns bytes written (>0). Guarded: !buf or count<2 -> -ENOSPC
 *    (stock would underflow buf[count-2] there).
 * All three are plain EXPORT_SYMBOL (never _GPL): hnd.ko/wl.ko are
 * Proprietary-licensed and cannot see _GPL exports.
 *
 * SEED (L1 factory image + L3 per-unit params; L2 userspace corpus
 * deliberately excluded — see SHIM_LANE_G_REPORT.md §2):
 *  L1 = shim_nvram_seed.h, generated by tools/nvram_seed_gen.py from
 *       triaging/shim/96764SV1.nvm (stock manufacturing board image,
 *       462 records: boardtype/boardrev/sromrev, sb/0+sb/1 PHY calibration,
 *       wl_mlo_config, factory MAC placeholders).
 *  L3 = module params below, applied after L1 (override factory MACs with
 *       per-unit values; lane H refreshes them from live stock with
 *       `nvram kget sb/0/macaddr` / `sb/1/macaddr` / `et0macaddr`).
 *
 * OBSERVABILITY (lane-G key table): the first 32 k_get misses are each
 * logged (pr_warn with key name) — that IS the "which key does the blob
 * ask first" instrument; afterwards a once-summary counts the rest.
 * getall/k_set-slow-paths use pr_warn_once per SHIM_WORKPLAN §F.
 */
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/string.h>
#include <linux/slab.h>
#include <linux/list.h>
#include <linux/spinlock.h>
#include <linux/atomic.h>
#include <linux/etherdevice.h>
#include <linux/errno.h>
#include "shim.h"
#include "shim_nvram_seed.h"

/* --- module params: per-unit identity without rebuilding ---
 * et0macaddr default provenance: kept at the pre-existing
 * 02:10:18:00:00:01 (base of our 6.6 locally-administered scheme; our eth0
 * is :02). NOT verified against stock: the factory image carries
 * 00:90:4C:56:71:47 and the live unit value comes from `bdinfo mac`
 * (hndnvram.sh derives sb/0=+2, sb/1=+3 from it). Lane H: confirm with
 * `router.sh stock 'nvram kget et0macaddr'` and override at insmod.
 * wl0/wl1_hwaddr default to "" = "derive from et0macaddr +2/+3", mirroring
 * the stock bdinfo convention (hndnvram.sh nvram_macaddr_check_update).
 * Explicit values override the derivation. All three params are ALSO
 * seeded into the store (keys et0macaddr, sb/0/macaddr, sb/1/macaddr),
 * so one insmod line fixes kerSysGetMacAddress and the store together. */
static char *et0macaddr = "02:10:18:00:00:01";
module_param(et0macaddr, charp, 0444);
MODULE_PARM_DESC(et0macaddr, "base MAC; also seeds store key et0macaddr");

static char *wl0_hwaddr = "";
module_param(wl0_hwaddr, charp, 0444);
MODULE_PARM_DESC(wl0_hwaddr, "sb/0/macaddr override (\"\" = et0macaddr+2)");

static char *wl1_hwaddr = "";
module_param(wl1_hwaddr, charp, 0444);
MODULE_PARM_DESC(wl1_hwaddr, "sb/1/macaddr override (\"\" = et0macaddr+3)");

/* H6 stock kget returned these four tokens WITHOUT the .nvm file's
 * surrounding quotes. Passing the raw file representation makes hnd
 * reject the list ("must have 4 values" in the H6 log). */
static char *wl_mlo_config = "0 1 -1 -1";
module_param(wl_mlo_config, charp, 0444);
MODULE_PARM_DESC(wl_mlo_config, "kernel nvram MLO radio mapping (unquoted value)");

/* board.h:346: int kerSysGetMacAddress(unsigned char *addr, unsigned long id).
 * Returns 0 on success; MUST fill the buffer (hnd sprintf's it without
 * checking — subagent B, SHIM_B_SUMMARY §2.29). Serves the module-param
 * MAC, bumping the last octet per id (long-standing convention of this
 * shim; matches the wl0/wl1 +2/+3 derivation above for small ids). */
int kerSysGetMacAddress(unsigned char *pucaAddr, unsigned long ulId)
{
	u8 mac[ETH_ALEN];

	if (!pucaAddr)
		return -EINVAL;
	if (!mac_pton(et0macaddr, mac)) {
		pr_err("bcm_shim: bad et0macaddr param '%s'\n", et0macaddr);
		return -EINVAL;
	}
	mac[ETH_ALEN - 1] += (u8)(ulId & 0xff);
	memcpy(pucaAddr, mac, ETH_ALEN);
	return 0;
}
EXPORT_SYMBOL(kerSysGetMacAddress);

/* --- in-RAM key=value store (replaces stock wlcsm rbtree; the blob only
 * ever sees char* values and the getall byte stream, so a list is
 * ABI-identical and far easier to audit). --- */
struct shim_nvram_entry {
	struct list_head node;
	char *name;
	char *value;
};

static LIST_HEAD(shim_nvram_list);
static DEFINE_SPINLOCK(shim_nvram_lock);

/* Miss observability: log each of the first N misses (key discovery for
 * lane H), then a single summary. Counter is outside the lock (atomic). */
#define SHIM_NVRAM_MISS_LOG_N 32
static atomic_t shim_nvram_miss_count = ATOMIC_INIT(0);

static struct shim_nvram_entry *shim_nvram_find_locked(const char *name)
{
	struct shim_nvram_entry *e;

	list_for_each_entry(e, &shim_nvram_list, node) {
		if (!strcmp(e->name, name))
			return e;
	}
	return NULL;
}

/* wlcsm_nvram.c:210 — miss returns NULL (hnd getvar_internal and wl.ko
 * wl_pktfwd_sys_init both NULL-check). Hit returns a pointer to the
 * stored value (NOT a copy — same contract as stock). */
char *wlcsm_nvram_k_get(char *name)
{
	struct shim_nvram_entry *e;
	char *val;
	unsigned long flags;
	int n;

	if (!name)
		return NULL;
	spin_lock_irqsave(&shim_nvram_lock, flags);
	e = shim_nvram_find_locked(name);
	val = e ? e->value : NULL;
	spin_unlock_irqrestore(&shim_nvram_lock, flags);
	if (!val) {
		n = atomic_inc_return(&shim_nvram_miss_count);
		if (n <= SHIM_NVRAM_MISS_LOG_N)
			pr_warn("bcm_shim: nvram miss #%d: '%s'\n", n, name);
		else if (n == SHIM_NVRAM_MISS_LOG_N + 1)
			shim_warn_once("nvram miss log capped at %d, "
				       "further misses unlogged (total counted)\n",
				       SHIM_NVRAM_MISS_LOG_N);
	}
	return val;
}
EXPORT_SYMBOL(wlcsm_nvram_k_get);

/* wlcsm_nvram.c:226 — 0 on success, WLCSM_GEN_ERR(1) on error. May sleep
 * (kstrdup GFP_KERNEL): matches stock call context (process context;
 * hnd calls via si_attach/ioctl paths, wl.ko via module init).
 * The exported wrapper keeps the GPL-exact `char *` signature (ABI is
 * pointer-identical anyway); the const-correct worker is used internally
 * so the seed table stays `const char *`. */
static int shim_nvram_k_set_worker(const char *name, const char *value)
{
	struct shim_nvram_entry *e, *ne;
	char *nname, *nval;
	unsigned long flags;

	if (!name || !*name) {
		shim_warn_once("nvram_k_set: empty name rejected\n");
		return 1;
	}
	if (!value)
		value = ""; /* DEVIATION from stock, see file header. */
	nname = kstrdup(name, GFP_KERNEL);
	nval = kstrdup(value, GFP_KERNEL);
	if (!nname || !nval) {
		kfree(nname);
		kfree(nval);
		shim_warn_once("nvram_k_set: OOM for '%s'\n", name);
		return 1;
	}
	spin_lock_irqsave(&shim_nvram_lock, flags);
	e = shim_nvram_find_locked(name);
	if (e) {
		kfree(e->value);
		e->value = nval;
		kfree(nname);
	} else {
		ne = kmalloc(sizeof(*ne), GFP_ATOMIC);
		if (!ne) {
			spin_unlock_irqrestore(&shim_nvram_lock, flags);
			kfree(nname);
			kfree(nval);
			shim_warn_once("nvram_k_set: OOM entry for '%s'\n",
				       name);
			return 1;
		}
		ne->name = nname;
		ne->value = nval;
		list_add_tail(&ne->node, &shim_nvram_list);
	}
	spin_unlock_irqrestore(&shim_nvram_lock, flags);
	return 0;
}

int wlcsm_nvram_k_set(char *name, char *value)
{
	return shim_nvram_k_set_worker(name, value);
}
EXPORT_SYMBOL(wlcsm_nvram_k_set);

/* wlcsm_nvram.c:278 + wlcsm_double_null_terminate — "name=value\\0" per
 * entry, whole buffer double-NUL terminated; returns bytes written.
 * Truncation behaviour mirrors stock (stop adding, pin last two bytes
 * NUL); hnd only tests the return for >0 (nvram_getall wrapper:
 * r0>0 -> 0/success). */
int wlcsm_nvram_getall(char *buf, int count)
{
	struct shim_nvram_entry *e;
	unsigned long flags;
	int len = 0, nlen;

	if (!buf || count < 2)
		return -ENOSPC;
	spin_lock_irqsave(&shim_nvram_lock, flags);
	list_for_each_entry(e, &shim_nvram_list, node) {
		nlen = strlen(e->name) + 1 + strlen(e->value) + 1;
		if (len + nlen + 1 > count)
			break;
		len += scnprintf(buf + len, count - len, "%s=%s",
				 e->name, e->value) + 1;
	}
	/* double-NUL terminate (stock wlcsm_double_null_terminate): the
	 * loop above always leaves room for one more NUL by construction. */
	buf[len++] = '\0';
	spin_unlock_irqrestore(&shim_nvram_lock, flags);
	return len;
}
EXPORT_SYMBOL(wlcsm_nvram_getall);

/* Bump a "xx:xx:xx:xx:xx:xx" MAC by add (8-bit wrap, stock U-Boot style).
 * Returns 0 on success. */
static int shim_mac_bump(const char *src, u8 add, char *dst, size_t dstlen)
{
	u8 mac[ETH_ALEN];

	if (!mac_pton(src, mac))
		return -EINVAL;
	mac[ETH_ALEN - 1] += add;
	snprintf(dst, dstlen, "%pM", mac);
	return 0;
}

int shim_nvram_init(void)
{
	size_t i;
	int seeded = 0;
	char macbuf[18];

	/* L1: factory board image (worker takes const directly). */
	for (i = 0; i < SHIM_NVRAM_SEED_N; i++)
		if (!shim_nvram_k_set_worker(shim_nvram_seed[i].name,
					     shim_nvram_seed[i].value))
			seeded++;

	/* L3: per-unit MACs override the factory placeholders. */
	if (shim_nvram_k_set_worker("wl_mlo_config", wl_mlo_config))
		return -ENOMEM;
	if (shim_nvram_k_set_worker("et0macaddr", et0macaddr))
		pr_warn("bcm_shim: seed et0macaddr failed\n");
	if (!wl0_hwaddr[0] && !shim_mac_bump(et0macaddr, 2, macbuf,
					     sizeof(macbuf)))
		shim_nvram_k_set_worker("sb/0/macaddr", macbuf);
	else if (wl0_hwaddr[0])
		shim_nvram_k_set_worker("sb/0/macaddr", wl0_hwaddr);
	if (!wl1_hwaddr[0] && !shim_mac_bump(et0macaddr, 3, macbuf,
					     sizeof(macbuf)))
		shim_nvram_k_set_worker("sb/1/macaddr", macbuf);
	else if (wl1_hwaddr[0])
		shim_nvram_k_set_worker("sb/1/macaddr", wl1_hwaddr);

	pr_info("bcm_shim: nvram backend up (%d/%u seed keys, MAC base %s)\n",
		seeded, (unsigned)SHIM_NVRAM_SEED_N, et0macaddr);
	return 0;
}
